spring:
#  profiles.active: local
  application:
     name: webUI
eureka:
  client:
    registerWithEureka: false
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://${vcap.services.eureka-service.credentials.uri:127.0.0.1:8761}/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost} 
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

hystrix:
  command:
    getQuote:
      execution.isolation.thread.timeoutInMilliseconds: 1000
    getCompanies:
      execution.isolation.thread.timeoutInMilliseconds: 1000
    getPortfolioValue:
      execution.isolation.thread.timeoutInMilliseconds: 500

foo: bar
company: Company XYZ
latency: true
newparam: 123


---
spring:
  profiles: local
  jpa:
     hibernate:
        ddl-auto: update
server:
  port: 8080
eureka:
  instance:
    nonSecurePort: ${server.port}
---
spring:
  profiles: cloud
  jpa:
     hibernate:
        ddl-auto: update

---
logging:
  level:
     io:
        pivotal: DEBUG
     org:
        springframework:
           web: WARN
           cloud: WARN
     com:
       netflix:
         hystrix: DEBUG